### PR TITLE
feat: update reference to image to point to rock

### PR DESCRIPTION
**Pull request by i-chvets**
# Description

Integration of Argo Exec ROCK. Updating all required configuratoin files.

# Summary of changes:
- Updated config.yaml to refer to published ROCK image instead of upstream container image. Version of workload is 3.3.10.

# Testing

Related PRs:
https://github.com/canonical/argo-workflows-rocks/pull/10

### CODE REVIEW

**Review by DnPlas — COMMENTED** [review]
Thanks @i-chvets 

If we approve and merge this PR, we would be reverting the argo 3.3.10 upgrades (we are now using the container image and CRDs 3.3.10). If we really want to integrate argo-controller with its corresponding rock, I suggest we first build and publish the newer version of the container image.

**Comment by i-chvets** [comment]
> Thanks @i-chvets
> 
> If we approve and merge this PR, we would be reverting the argo 3.3.10 upgrades (we are now using the container image and CRDs 3.3.10). If we really want to integrate argo-controller with its corresponding rock, I suggest we first build and publish the newer version of the container image.

I don't understand. Currently, we have version 3.3.8 in `main` and we are updating it to reference ROCK with the same version. What changes are being reverted by this PR exactly?

**Comment by DnPlas** [comment]
> > Thanks @i-chvets
> > If we approve and merge this PR, we would be reverting the argo 3.3.10 upgrades (we are now using the container image and CRDs 3.3.10). If we really want to integrate argo-controller with its corresponding rock, I suggest we first build and publish the newer version of the container image.
> 
> @DnPlas I don't understand. Currently, we have version 3.3.8 in `main` and we are updating it to reference ROCK with the same version. What changes are being reverted by this PR exactly?
> 
> We can postpone this work and move corresponding Jira to Blocked until we start doing 1.8 work for Seldon. @kimwnasptd What is your opinion on this?

We have [`argo-controller` in 3.3.10 already](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/metadata.yaml#L15), and argo-server will soon be on that version as well https://github.com/canonical/argo-operators/pull/130, if we merge this PR, we will be bringing back an older version of those components.

**Comment by i-chvets** [comment]
> 
> We have [`argo-controller` in 3.3.10 already](https://github.com/canonical/argo-operators/blob/main/charms/argo-controller/metadata.yaml#L15), and argo-server will soon be on that version as well #130, if we merge this PR, we will be bringing back an older version of those components.

I see. #130 is not merged though. Anyway, let's bump it to 3.3.10. I will need to spin another version of the ROCK for this.

**Comment by i-chvets** [comment]
@DnPlas Bumped version to 3.3.10.

**Review by DnPlas — APPROVED** [review]
Thanks @i-chvets, LGTM

**Pull request merged**
